# 1D Numpy in Python


### What is Numpy?

NumPy is a Python library used for working with arrays, linear algebra, fourier transform, and matrices. NumPy stands for Numerical Python and it is an open source project. The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

NumPy is usually imported under the np alias.

It's usually fixed in size and each element is of the same type. We can cast a list to a numpy array by first importing numpy:

In [ ]:
# import numpy library

import numpy as np 

In [2]:
# Create a numpy array
import numpy as np
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [3]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [4]:
a.ndim

1

In [5]:
type(a)

numpy.ndarray

In [6]:
# Create numpy array

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [7]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [8]:
# Assign the 5th element to 0

c[4] = 0
c

array([100,   1,   2,   3,   0])

In [9]:
a = np.array([10, 2, 30, 40,50])

# Enter your code here
a[1]=20
a

array([10, 20, 30, 40, 50])

#### Slicing

Like lists, we can slice the numpy array. Slicing in python means taking the elements from the given index to another given index.

We pass slice like this: [start:end].The element at end index is not being included in the output.

We can select the elements from 1 to 3 and assign it to a new numpy array d as follows:

In [10]:
# Slicing the numpy array

d = c[1:4]
d

array([1, 2, 3])

In [11]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

We can also define the steps in slicing, like this: [start:end:step].

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [14]:
print(arr[:4])
print(arr[4:])
print(arr[1:5:])

[1 2 3 4]
[5 6 7]
[2 3 4 5]


In [ ]:
# Get the size of numpy array

a.size


In [ ]:
# Get the shape/size of numpy array

a.shape

## Numpy Statistical Functions

In [15]:
# Create a numpy array

a = np.array([1, -1, 1, -1])

In [16]:
# Get the mean of numpy array

mean = a.mean()
mean

np.float64(0.0)

In [17]:
# Get the standard deviation of numpy array

standard_deviation=a.std()
standard_deviation

np.float64(1.0)

In [18]:
# Create a numpy array

b = np.array([-1, 2, 3, 4, 5])
b

array([-1,  2,  3,  4,  5])

In [19]:
# Get the biggest value in the numpy array

max_b = b.max()
max_b

np.int64(5)

In [ ]:
# Get the smallest value in the numpy array

min_b = b.min()
min_b

### Numpy Array Operations

#### Array Addition

In [20]:
u = np.array([1, 0])
v = np.array([0, 1])
# Numpy Array Addition

z = np.add(u, v)
z

array([1, 1])

### Array Subtraction

In [21]:
a = np.array([10, 20, 30])
b = np.array([5, 10, 15])
c = np.subtract(a, b)

print(c)

[ 5 10 15]


### Array Multiplication

In [22]:
x = np.array([1, 2])
y = np.array([2, 1])
# Numpy Array Multiplication

z = np.multiply(x, y)
z

array([2, 2])

### Array Division

In [23]:
a = np.array([10, 20, 30])
b = np.array([2, 10, 5])
c = np.divide(a, b)
c

array([5., 2., 6.])

### Dot Product

In [24]:
z= np.array([1,2])
x= np.array([3,2])
np.dot(z,x)

np.int64(7)

#### Adding Constant to a Numpy Array

In [25]:
u = np.array([1, 2, 3, -1]) 
u + 1
u

array([ 1,  2,  3, -1])

#### Mathematical Functions

In [26]:
# The value of pi

np.pi 

3.141592653589793

In [27]:
# Create the numpy array in radians

x = np.array([0, np.pi/2 , np.pi])


We can apply the function sin to the array x and assign the values to the array y; this applies the sine function to each element in the array

In [28]:
# Calculate the sin of each elements

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

### Linspace

A useful function for plotting mathematical functions is linspace. Linspace returns evenly spaced numbers over a specified interval.

##### numpy.linspace(start, stop, num = int value)

start : start of interval range

stop : end of interval range

num : Number of samples to generate.

In [29]:
# Makeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2, 2, num=5) #num means How many number you want

array([-2., -1.,  0.,  1.,  2.])


If we change the parameter num to 9, we get 9 evenly spaced numbers over the interval from -2 to 2:

In [33]:
# Make a numpy array within [0,2pi] and 100 elements
np.linespace(0,2*np.pi, num = 100)

AttributeError: module 'numpy' has no attribute 'linespace'

We can apply the sine function to each element in the array x and assign it to the array y: